# Generated by Django 4.2.3 on 2023-07-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothing',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
